version: 2
jobs:
  build:

    working_directory: ~/test-rest

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - setup_remote_docker

#      - restore_cache:
#          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
#
#      - run: mvn dependency:go-offline
#
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: gradle build

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: build/libs/test-rest-0.0.1-SNAPSHOT.jar

      - run:
          name: build and push Docker image
          command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t spike234/test-rest:$TAG .
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push spike234/test-rest:$TAG